# Azure Virtual Machine Configurations for Az-Burrow
# This file defines your Azure VMs that can be used to create SSH tunnels via Azure Bastion
#
# Usage:
#   ./az-burrow                           # Uses burrow.config.yaml or tunnels.yaml in current directory
#   ./az-burrow /path/to/config.yaml      # Uses specified config file
#
# For more information: https://github.com/hegde-atri/az-burrow
#
# Each machine entry requires the following fields:

machines:
  # Example VM configuration with SSH certificate auto-renewal
  - name: vm-uk-experiment-01 # Display name for this VM (shown in the TUI selection menu)

    # The Azure resource group containing this virtual machine
    resource_group: LAB-UK

    # The full Azure resource ID of the VM
    # Format: /subscriptions/{subscription-id}/resourceGroups/{rg-name}/providers/Microsoft.Compute/virtualMachines/{vm-name}
    # Find this in Azure Portal: VM → Properties → Resource ID
    target_resource_id: /subscriptions/Microsoft.Compute/virtualMachines/valid-id

    # The name of the Azure Bastion host used for creating the tunnel
    # This Bastion must have connectivity to the target VM
    bastion_name: bastion-name

    # The resource group containing the Azure Bastion host
    # May differ from the VM's resource group in hub-spoke architectures
    bastion_resource_group: RG-HUB

    # The subscription containing the Azure Bastion host
    # May differ from the VM's resource group in hub-spoke architectures
    bastion_subscription: SUB-HUB

    # Optional: SSH Configuration for automatic certificate management
    # If provided, az-burrow will automatically monitor and renew SSH certificates
    ssh_config_path: ~/.ssh/az_ssh_config/azure-bastion-vm

  # Additional VM example
  - name: vm-api-dev
    resource_group: DEV-API
    target_resource_id: /subscriptions/Microsoft.Compute/virtualMachines/valid-id
    bastion_name: bastion-name
    bastion_resource_group: RG-HUB
